### ISSUE TITLE
Can't log in to Queue

### ISSUE THREAD

**Issue by jin7867** [Serivy/StreamTheory#47]
hello, I've downloaded the extension but I when I run it
the bottom image pops up. also I cant seem to log in to the admin website 

![image](https://user-images.githubusercontent.com/102138182/159423213-b2ae2806-c688-4edc-9657-0b33da5adb9c.png)

![image](https://user-images.githubusercontent.com/102138182/159423907-b977ded7-e32f-4b53-a9ab-1c069ba0d796.png)

**Comment by Serivy** [comment]
Thanks for reaching out. I see the error and I think it is now fixed. Can you try again and let me know if it works?

**Comment by jin7867** [comment]
Thanks, the extension is working 
However, I am still unable to access admin page.  
![image](https://user-images.githubusercontent.com/102138182/159443516-5aaecf78-326b-4849-b197-a850ed34c259.png)

**Comment by Serivy** [comment]
Interesting, I will take another look

**Comment by Serivy** [comment]
This problem should now be fixed. 

Keep in mind the only reason to log into the website now is to update your subscriber list, I intend an update coming soon which will no longer require this as it can come the the users in twitch directly.
